Allow specifying additional aspects to tut
bazelbuild/bazel-skylib pull request #299
Opened 2021-05-24 16:17 UTC by illicitonion

To simulate this in a test I had to define a separate attribute with the
aspect applied and ignore `target_under_test`, except because
`target_under_test` is mandatory I had to set some value for it which
was ignored.

This may or may not fix
https://github.com/bazelbuild/bazel-skylib/issues/189 (I could see also
wanting a `build_test`-like target which builds with an aspect - I'm not
entirely sure what the scope of that issue was meant to be :))

2021-05-27 07:00 UTC, hlopko commented
+1, without this PR or other solution to #189 I am not able to conveniently unit test aspects. My workaround is to create an artificial rule that applies the aspect on its attribute, and collects the aspect outputs, but I'm still not able to make assertions about providers provided by the aspect on targets it's attached to.

I'm happy to write up a longer problem description if ^ is not clear enough.

2021-07-22 17:16 UTC, illicitonion commented
@tetromino - would you mind taking a quick look? Thanks!

2021-08-24 23:42 UTC, UebelAndre commented
@brandjon @tetromino would you be able to take a look here? 😅 🙏

2021-09-07 18:35 UTC, tetromino requested changes
Looks good, but can you please add a small test to tests/unittest_tests.bzl and unittest_test.sh?

2021-09-23 20:21 UTC, tetromino approved these changes
Thanks for the test!

2021-09-23 20:21 UTC, merged