copy_file allows directories as well
bazelbuild/bazel-skylib pull request #323
Opened 2021-10-09 18:43 UTC by alexeagle

Fixes #322

2021-11-10 17:20 UTC, lencioni commented
@brandjon @tetromino do you have any feedback on this PR? I believe this will help unblock using rules_nodejs with remote build execution, which would be really nice to see!

2022-01-09 14:21 UTC, alexeagle commented
Ping! Is anyone triaging PRs in this repo?
If not we'll probably switch rules_nodejs to use https://github.com/aspect-build/bazel-lib where we can get fixes like this.

2022-01-10 18:16 UTC, tetromino requested changes

2022-01-10 18:16 UTC, tetromino commented on rules/private/copy_file_private.bzl
> +        cmd_tmpl = "@xcopy \"%s\" \"%s\\\" /V /E /H /Y /Q >NUL"
Why use /v for xcopy, but not for copy?

Why delete the destination directory in the bash version, but not in the Windows version?

2022-01-10 18:31 UTC, tetromino requested changes
Overall - looks good; thank you for the patch!

However, I would prefer a separate copy_directory rule: less confusing name (files aren't directories), no confusing interaction between is_directory and allow_symlinks flags, more noticeable documentation of DBAZEL_TRACK_SOURCE_DIRECTORIES.

The one new test is insufficient. Scenarios we'd probably want to test:
* copying an empty directory
* copying a directory whose content includes a symlink
* copying a directory to a location which is an existing file
* copying a directory to a location which is an existing directory

2022-04-13 16:17 UTC, alexeagle commented
replaced by #366

2022-04-13 16:17 UTC, closed without merging