Improve user feedback for run_binary location expansions
bazelbuild/bazel-skylib pull request #490
Opened 2024-03-02 15:53 UTC by UebelAndre

A common point of confusion I see around `run_binary` is that it's hard coded to only expand `$(location` values which in codebases I work in are otherwise completely eliminated due to it being described as "legacy"

> location: A synonym for either execpath or rootpath, depending on the attribute being expanded. This is legacy pre-Starlark behavior and not recommended unless you really know what it does for a particular rule. See [#2475](https://github.com/bazelbuild/bazel/issues/2475#issuecomment-339318016) for details.

If `execpath` is used instead as the appropriate alternative, the rule does no do any expansion and fails the action. This change adds support for `$(execpath` and adds logging that informs users other expansions will be ignored.

2024-04-06 01:42 UTC, UebelAndre commented
@tetromino any chance you have time to review this?

2024-04-24 20:09 UTC, tetromino requested changes

2024-04-24 20:09 UTC, tetromino commented on rules/run_binary.bzl
> +def _is_expandable(value):
This check is misleading; if the template contains both `$(location ...)` and `$(rlocationpath ...)`, *both* will be expanded.

I think we ought to allow people to expand `$(rlocationpath` etc. - I don't see a use case for it, but going out of our way to filter it out complicates the code for no good reason.

2024-04-25 12:18 UTC, UebelAndre commented on rules/run_binary.bzl
> +        ctx.expand_location(a, tool_as_list) if _is_expandable("$(location") else a
Oops! Yes!

2024-04-30 14:33 UTC, UebelAndre commented
@tetromino you available for another pass?

2024-04-30 21:13 UTC, tetromino approved these changes
LGTM. I've taken the liberty of updating the docs to mention both `$(execpath)` and `$(location)`.

2024-04-30 21:19 UTC, merged